# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/gravatar_image_tag/all/gravatar_image_tag.rbi
#
# gravatar_image_tag-1.2.0

module GravatarImageTag
  def self.configuration; end
  def self.configuration=(arg0); end
  def self.configure; end
  def self.gravatar_id(email, filetype = nil); end
  def self.gravatar_options(overrides = nil); end
  def self.gravatar_url(email, overrides = nil); end
  def self.gravatar_url_base(secure = nil); end
  def self.included(base); end
  def self.url_params(gravatar_params); end
  def self.value_cleaner(value); end
end
class GravatarImageTag::Configuration
  def default_image; end
  def default_image=(arg0); end
  def filetype; end
  def filetype=(arg0); end
  def include_size_attributes; end
  def include_size_attributes=(arg0); end
  def initialize; end
  def rating; end
  def rating=(arg0); end
  def secure; end
  def secure=(arg0); end
  def size; end
  def size=(arg0); end
end
module GravatarImageTag::ClassMethods
  def default_gravatar_filetype=(value); end
  def default_gravatar_image=(value); end
  def default_gravatar_rating=(value); end
  def default_gravatar_size=(value); end
  def secure_gravatar=(value); end
end
module GravatarImageTag::InstanceMethods
  def gravatar_image_tag(email, options = nil); end
  def gravatar_image_url(email, gravatar_overrides = nil); end
end
class ActionView::Base
  extend GravatarImageTag::ClassMethods
  include GravatarImageTag
  include GravatarImageTag::InstanceMethods
end
