# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/guard-sorbet/all/guard-sorbet.rbi
#
# guard-sorbet-0.5.0

module Guard
end
class Guard::Sorbet < Guard::Plugin
  def initialize(*args, &blk); end
  def run_all(*args, &blk); end
  def run_on_modifications(*args, &blk); end
  def start(*args, &blk); end
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
