# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/pronto-stylelint/all/pronto-stylelint.rbi
#
# pronto-stylelint-0.10.0

module Pronto
end
class Pronto::Stylelint < Pronto::Runner
  def clean_up_stylelint_output(output); end
  def cli_options; end
  def cli_options=(arg0); end
  def files_to_lint; end
  def files_to_lint=(regexp); end
  def git_repo_path; end
  def initialize(patches, commit = nil); end
  def inspect(patch); end
  def new_message(offence, line); end
  def read_config; end
  def run; end
  def run_stylelint(patch); end
  def style_file?(path); end
  def stylelint_executable; end
  def stylelint_executable=(arg0); end
end
