# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/pronto-fasterer/all/pronto-fasterer.rbi
#
# pronto-fasterer-0.10.0

module Pronto
end
class Pronto::Fasterer < Pronto::Runner
  def config; end
  def inspect(patch); end
  def new_message(error, line); end
  def run; end
end
