# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/pronto-eslint_npm/all/pronto-eslint_npm.rbi
#
# pronto-eslint_npm-0.10.1

module Pronto
end
class Pronto::ESLintNpm < Pronto::Runner
  def clean_up_eslint_output(output); end
  def cmd_line_opts; end
  def cmd_line_opts=(arg0); end
  def config_options; end
  def eslint_command_line(path); end
  def eslint_executable; end
  def eslint_executable=(arg0); end
  def files_to_lint; end
  def files_to_lint=(regexp); end
  def inspect(patch); end
  def js_file?(path); end
  def new_message(offence, line); end
  def read_config; end
  def repo_path; end
  def run; end
  def run_eslint(patch); end
end
