# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/pronto-sorbet/all/pronto-sorbet.rbi
#
# pronto-sorbet-0.2.0

module Pronto
end
module Pronto::Sorbet
end
class Pronto::Sorbet::Runner < Pronto::Runner
  def run; end
  def sorbet_errors; end
  def sorbet_executable; end
end
