# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/pronto-json/all/pronto-json.rbi
#
# pronto-json-0.1.5

module Pronto
end
module Pronto::Json
end
class Pronto::Json::Runner < Pronto::Runner
  def detect_line(candidate_lines, error_line_no); end
  def inspect(patch); end
  def json_file?(path); end
  def line_number(line); end
  def new_message(error, line); end
  def oj_error(error); end
  def run; end
end
