# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/pronto-rubocop/all/pronto-rubocop.rbi
#
# pronto-rubocop-0.10.0

module Pronto
end
class Pronto::Rubocop < Pronto::Runner
  def run; end
end
class Pronto::Rubocop::PatchCop
  def config; end
  def initialize(patch, runner); end
  def level(severity); end
  def messages; end
  def new_message(offence, line); end
  def offences; end
  def patch; end
  def path; end
  def processed_source; end
  def registry; end
  def runner; end
  def team; end
  def valid?; end
end
