# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/pronto-brakeman/all/pronto-brakeman.rbi
#
# pronto-brakeman-0.10.0

module Pronto
end
class Pronto::Brakeman < Pronto::Runner
  def messages_for(ruby_patches, output); end
  def new_message(line, warning); end
  def patch_for_warning(ruby_patches, warning); end
  def run; end
  def severity_for_confidence(confidence_level); end
end
