# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/pronto-shellcheck/all/pronto-shellcheck.rbi
#
# pronto-shellcheck-0.1.4

module Pronto
end
class Pronto::ShellCheckRunner < Pronto::Runner
  def inspect(patch); end
  def new_message(offence, line); end
  def repo_path; end
  def run; end
  def run_shellcheck(patch); end
  def self.file_has_shebang?(path); end
  def self.path_has_extension?(path); end
  def self.regular_file?(path); end
  def self.shellcheckable?(path); end
  def shellcheck_opts; end
  def shellcheckable?(*args, &block); end
  extend Forwardable
end
