# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/pronto-bundler_audit/all/pronto-bundler_audit.rbi
#
# pronto-bundler_audit-0.6.0

module Pronto
end
module Pronto::Formatter
end
class Pronto::Formatter::GithubPullRequestReviewFormatter < Pronto::Formatter::PullRequestFormatter
end
class Pronto::BundlerAudit < Pronto::Runner
  def commit_sha; end
  def filename; end
  def path; end
  def run; end
  def self.configuration; end
end
class Pronto::BundlerAudit::Configuration
  def configuration; end
  def configuration_file; end
  def ignored_advisories; end
  def initialize(path: nil); end
end
module Pronto::BundlerAuditVersion
end
module Pronto::BundlerAudit::Results
end
class Pronto::BundlerAudit::Results::BaseResult
  def initialize(scan_result); end
  def level; end
  def line; end
  def message; end
end
class Pronto::BundlerAudit::Results::InsecureSource < Pronto::BundlerAudit::Results::BaseResult
  def level; end
  def line; end
  def message; end
end
module Pronto::BundlerAudit::AdvisoryFormatters
end
class Pronto::BundlerAudit::AdvisoryFormatters::BaseAdvisoryFormatter
  def advisory_criticality; end
  def advisory_description; end
  def advisory_solution; end
  def advisory_title; end
  def advisory_url; end
  def any_patched_versions?; end
  def gem_name; end
  def gem_version; end
  def initialize(gem:, advisory:); end
  def patched_versions; end
  def to_s; end
end
class Pronto::BundlerAudit::AdvisoryFormatters::Compact < Pronto::BundlerAudit::AdvisoryFormatters::BaseAdvisoryFormatter
  def to_s; end
end
class Pronto::BundlerAudit::AdvisoryFormatters::Verbose < Pronto::BundlerAudit::AdvisoryFormatters::BaseAdvisoryFormatter
  def to_s; end
end
module Pronto::BundlerAudit::GemfileLock
end
class Pronto::BundlerAudit::GemfileLock::Scanner
  def call; end
  def determine_relevant_line_number; end
  def initialize(gem_name:, path: nil); end
  def self.call(*args); end
end
class Pronto::BundlerAudit::Results::UnpatchedGem < Pronto::BundlerAudit::Results::BaseResult
  def advisory_formatter; end
  def find_relevant_line_number; end
  def level; end
  def line; end
  def message; end
end
class Pronto::BundlerAudit::Scanner
  def call; end
  def match_result(scan_result); end
  def run_scan; end
  def run_scanner(ignored_advisories: nil); end
  def self.call(*args); end
end
class Pronto::BundlerAudit::Auditor
  def call; end
  def run_scanner; end
  def self.call(*args); end
  def update_ruby_advisory_db; end
end
class Pronto::BundlerAudit::Results::ProntoMessagesAdapter
  def call; end
  def initialize(results, runner:); end
  def self.call(*args); end
end
class Pronto::BundlerAudit::Results::ProntoMessagesAdapter::DeepLine
  def commit_sha; end
  def initialize(line_number:, path:); end
  def line_number; end
  def new_lineno; end
  def patch; end
  def path; end
  def repo; end
end
