# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/pronto-rails_best_practices/all/pronto-rails_best_practices.rbi
#
# pronto-rails_best_practices-0.10.0

module Pronto
end
class Pronto::RailsBestPractices < Pronto::Runner
  def messages_for(patches, errors); end
  def new_message(line, error); end
  def patch_for_error(patches, error); end
  def run; end
end
