# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/pwned/all/pwned.rbi
#
# pwned-2.0.2

module Pwned
  def self.pwned?(password, request_options = nil); end
  def self.pwned_count(password, request_options = nil); end
end
class Pwned::Error < StandardError
end
class Pwned::TimeoutError < Pwned::Error
end
class Pwned::Password
  def fetch_pwned_count; end
  def for_each_response_line(&block); end
  def hashed_password; end
  def hashed_password_prefix; end
  def hashed_password_suffix; end
  def initialize(password, request_options = nil); end
  def password; end
  def pwned?; end
  def pwned_count; end
  def request_headers; end
  def request_options; end
  def stream_response_lines(response, &block); end
  def with_http_response(url, &block); end
end
class NotPwnedValidator < ActiveModel::EachValidator
  def on_error; end
  def request_options; end
  def threshold; end
  def validate_each(record, attribute, value); end
end
class PwnedValidator < NotPwnedValidator
end
