version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: pairing
      POSTGRES_PASSWORD: pairing
      POSTGRES_DB: pairing_development
    volumes:
      - ./tmp/postgresql:/var/lib/postgresql
    ports:
      - 5432:5432
  redis-cache:
    image: redis
    restart: always
    volumes:
      - ./tmp/redis-cache:/data
    ports:
      - 6379:6379
  redis-sidekiq:
    image: redis
    restart: always
    volumes:
      - ./tmp/redis-sidekiq:/data
    ports:
      - 6380:6379
