# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.6'

gem 'activeadmin', '~> 2.7'
gem 'bcrypt', '~> 3.1'
gem 'bootsnap', '~> 1.4'
gem 'cocoon', '~> 1.2'
gem 'devise', '~> 4.7'
gem 'devise-bootstrapped', github: 'king601/devise-bootstrapped', branch: 'bootstrap4'
gem 'devise-pwned_password', '~> 0.1.9'
gem 'faraday', '~> 1.0'
gem 'faraday_middleware', '~> 1.0'
gem 'ginjo-omniauth-slack', '~> 2.5', require: 'omniauth-slack'
gem 'gravatar_image_tag', '~> 1.2'
gem 'guard-sorbet', '~> 0.5.0'
gem 'hiredis', '~> 0.6.3'
gem 'jbuilder', '~> 2.7'
gem 'marginalia', '~> 1.9'
gem 'omniauth', '~> 1.9'
gem 'pg', '~> 1.2'
gem 'pghero', '~> 2.7'
gem 'puma', '~> 5.3'
gem 'rails', '~> 6.0', '>= 6.0.3.2'
gem 'redis', '~> 4.2'
gem 'sass-rails', '~> 6.0'
gem 'sidekiq', '~> 6.1'
gem 'sidekiq-statistic', '~> 1.4'
gem 'sorbet-rails', '~> 0.7.0'
gem 'sorbet-runtime', '~> 0.5.5878'
gem 'strong_migrations', '~> 0.7.1'
gem 'turbolinks', '~> 5.2'
gem 'tzinfo-data', '~> 1.2', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'webpacker', '~> 5.2'

group :development, :test do
  gem 'bullet', '~> 6.1'
  gem 'byebug', '~> 11.1'
  gem 'dotenv-rails', '~> 2.7'
  gem 'fasterer', '~> 0.8.3'
  gem 'guard', '~> 2.16'
  gem 'guard-minitest', '~> 2.4'
  gem 'pronto', '~> 0.10.0'
  gem 'pronto-brakeman', '~> 0.10.0'
  gem 'pronto-bundler_audit', '~> 0.6.0'
  gem 'pronto-eslint_npm', '~> 0.10.1'
  gem 'pronto-fasterer', '~> 0.10.0'
  gem 'pronto-json', '~> 0.1.5'
  gem 'pronto-rails_best_practices', '~> 0.10.0'
  gem 'pronto-rails_schema', '~> 0.10.0'
  gem 'pronto-rubocop', '~> 0.10.0'
  gem 'pronto-shellcheck', '~> 0.1.4'
  gem 'pronto-sorbet', '~> 0.2.0'
  gem 'pronto-stylelint', '~> 0.10.0'
  gem 'rubocop', '~> 0.92.0'
  gem 'rubocop-minitest', '~> 0.10.1'
  gem 'rubocop-performance', '~> 1.7'
  gem 'rubocop-rails', '~> 2.7'
  gem 'rubocop-sorbet', '~> 0.4.1'
  gem 'sorbet', '~> 0.5.5923'
  gem 'terminal-notifier-guard', '~> 1.7'
end

group :development do
  gem 'annotate', '~> 3.1'
  gem 'better_errors', '~> 2.7'
  gem 'binding_of_caller', '~> 0.8.0'
  gem 'brakeman', '~> 4.9'
  gem 'bundler-audit', '~> 0.7.0'
  gem 'cancancan', '~> 3.1'
  gem 'database_consistency', '~> 0.8.8'
  gem 'listen', '~> 3.2'
  gem 'pundit', '~> 2.1'
  gem 'rails_best_practices', '~> 1.20'
  gem 'spring', '~> 2.1'
  gem 'spring-watcher-listen', '~> 2.0'
  gem 'strong_versions', '~> 0.4.4'
  gem 'web-console', '~> 4.0'
end

group :test do
  gem 'capybara', '~> 3.33'
  gem 'selenium-webdriver', '~> 3.142'
  gem 'webdrivers', '~> 4.4'
end
