default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pairing_development
  username: pairing
  password: pairing
  host: localhost
  port: 5432

test:
  <<: *default
  database: pairing_test
  username: pairing
  password: pairing
  host: localhost
  port: 5432

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
