name: CI
on: [push]

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: pairing
          POSTGRES_PASSWORD: pairing
          POSTGRES_DB: pairing_test
        ports: ["5432:5432"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6.6'

      - name: Ruby gem cache
        uses: actions/cache@v2.1.2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle config --local build.sassc --disable-march-tune-native
          bundle install --jobs 4 --retry 3

      - name: Setup Node
        uses: actions/setup-node@v2.1.1
        with:
          node-version: 10.13.0

      - name: Find yarn cache location
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: JS package cache
        uses: actions/cache@v2.1.2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install packages
        run: |
          yarn install --pure-lockfile
      
      - name: Setup db
        run: |
          bundle exec rails db:setup
          
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Pronto
        env: 
          PRONTO_GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRONTO_PULL_REQUEST_ID: ${{ steps.findPr.outputs.pr }}
        run: |
          bundle exec pronto run --formatters=github_status github_pr --commit=origin/main --exit-code

      - name: Run linters
        run: |
          bin/linters_ci

      - name: Run security checks
        run: |
          bin/security_checks_ci

  tests:
    name: Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: pairing
          POSTGRES_PASSWORD: pairing
          POSTGRES_DB: pairing_test
        ports: ["5432:5432"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6.6'

      - name: Ruby gem cache
        uses: actions/cache@v2.1.2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle config --local build.sassc --disable-march-tune-native
          bundle install --jobs 4 --retry 3

      - name: Setup Node
        uses: actions/setup-node@v2.1.1
        with:
          node-version: 10.13.0

      - name: Find yarn cache location
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: JS package cache
        uses: actions/cache@v2.1.2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install packages
        run: |
          yarn install --pure-lockfile

      - name: Setup test database
        env:
          RAILS_ENV: test
        run: |
          bundle exec rails db:setup

      - name: Configure inotify
        run: |
          sudo sysctl fs.inotify.max_user_instances=524288
          sudo sysctl fs.inotify.max_user_watches=524288
          sudo sysctl fs.inotify.max_queued_events=524288
          sudo sysctl -p

      - name: Run tests
        run: bundle exec rails test

      - name: Run system tests
        run: bundle exec rails test:system

  deploy:
    name: Deploy to dokku
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [linters, tests]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Deploy to dokku
        uses: idoberko2/dokku-deploy-github-action@v1
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            dokku-host: 'prettyrandom.net'
            app-name: 'pairing'

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.30.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: major
          WITH_V: true
